[package]
name = "apricot-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
apricot-core.workspace = true
apricot-media.workspace = true
apricot-updater.workspace = true
chrono.workspace = true
encoding_rs.workspace = true
reqwest.workspace = true
regex = "1"
serde_json.workspace = true
thiserror.workspace = true
tempfile = "3"
url.workspace = true
windows.workspace = true

[lints]
workspace = true
