from .shortcuts import ShortcutsUI
from .cookies import CookiesUI
from .equalizer import EqualizerUI
from .menus import MenusUI
from .search import SearchUI
from .player import PlayerUI
from .downloads import DownloadsUI
from .lists import ListsUI
from .system import SystemUI
from .events import EventsUI
from .misc import MiscUI